// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameChain = "chains"

// Chain mapped from table <chains>
type Chain struct {
	ID        int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt *time.Time     `gorm:"column:created_at;type:datetime(3)" json:"createdAt"`
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:datetime(3)" json:"updatedAt"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:idx_chains_deleted_at,priority:1" json:"deletedAt"`
	ChainName *string        `gorm:"column:chain_name;type:varchar(255)" json:"chainName"`
	IP        *string        `gorm:"column:ip;type:varchar(255)" json:"ip"`
	Port      *int32         `gorm:"column:port;type:int" json:"port"`
	Protocol  *string        `gorm:"column:protocol;type:varchar(255)" json:"protocol"`
	Key       *string        `gorm:"column:key;type:varchar(255)" json:"key"`
	NodeID    int64          `gorm:"column:node_id;type:bigint;not null" json:"nodeId"`
	Node      Node           `gorm:"foreignKey:ID;references:NodeID" json:"node"`
}

// TableName Chain's table name
func (*Chain) TableName() string {
	return TableNameChain
}
