// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameNodeChainMapping = "node_chain_mappings"

// NodeChainMapping mapped from table <node_chain_mappings>
type NodeChainMapping struct {
	NodeID  int64 `gorm:"column:node_id;type:bigint;not null" json:"nodeId"`
	ChainID int64 `gorm:"column:chain_id;type:bigint;not null" json:"chainId"`
}

// TableName NodeChainMapping's table name
func (*NodeChainMapping) TableName() string {
	return TableNameNodeChainMapping
}
