// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTrafficPlan = "traffic_plan"

// TrafficPlan mapped from table <traffic_plan>
type TrafficPlan struct {
	ID           int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt    *time.Time     `gorm:"column:created_at;type:datetime(3)" json:"createdAt"`
	UpdatedAt    *time.Time     `gorm:"column:updated_at;type:datetime(3)" json:"updatedAt"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:idx_udt_deleted_at,priority:1" json:"deletedAt"`
	TotalTraffic int64          `gorm:"column:total_traffic;type:bigint;not null;comment:消耗" json:"totalTraffic"` // 消耗
	Period       *int32         `gorm:"column:period;type:int" json:"period"`
	PlanName     *string        `gorm:"column:plan_name;type:varchar(255)" json:"planName"`
}

// TableName TrafficPlan's table name
func (*TrafficPlan) TableName() string {
	return TableNameTrafficPlan
}
