// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameUserRoleNodeMapping = "user_role_node_mappings"

// UserRoleNodeMapping mapped from table <user_role_node_mappings>
type UserRoleNodeMapping struct {
	UserID   *int32  `gorm:"column:user_id;type:int" json:"userId"`
	RoleCode *string `gorm:"column:role_code;type:varchar(255)" json:"roleCode"`
	NodeID   int32   `gorm:"column:node_id;type:int;not null" json:"nodeId"`
	Node     Node    `gorm:"foreignKey:ID;references:NodeID" json:"node"`
}

// TableName UserRoleNodeMapping's table name
func (*UserRoleNodeMapping) TableName() string {
	return TableNameUserRoleNodeMapping
}
