// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserDailyTraffic = "user_daily_traffic"

// UserDailyTraffic mapped from table <user_daily_traffic>
type UserDailyTraffic struct {
	CreatedAt    *time.Time     `gorm:"column:created_at;type:datetime(3)" json:"createdAt"`
	UpdatedAt    *time.Time     `gorm:"column:updated_at;type:datetime(3)" json:"updatedAt"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:idx_udt_deleted_at,priority:1" json:"deletedAt"`
	Date         time.Time      `gorm:"column:date;type:date;primaryKey" json:"date"`
	TotalTraffic int64          `gorm:"column:total_traffic;type:bigint;not null;comment:消耗" json:"totalTraffic"` // 消耗
	UserID       int32          `gorm:"column:user_id;type:int;primaryKey" json:"userId"`
}

// TableName UserDailyTraffic's table name
func (*UserDailyTraffic) TableName() string {
	return TableNameUserDailyTraffic
}
