// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameUserRoleChainMapping = "user_role_chain_mappings"

// UserRoleChainMapping mapped from table <user_role_chain_mappings>
type UserRoleChainMapping struct {
	UserID   *int32  `gorm:"column:user_id;type:int" json:"userId"`
	RoleCode *string `gorm:"column:role_code;type:varchar(255)" json:"roleCode"`
	ChainID  int32   `gorm:"column:chain_id;type:int;not null" json:"chainId"`
	Chain    Chain   `gorm:"foreignKey:ID;references:ChainID" json:"chain"`
}

// TableName UserRoleChainMapping's table name
func (*UserRoleChainMapping) TableName() string {
	return TableNameUserRoleChainMapping
}
